# -------------------------
# Stage 1: Builder
# -------------------------
FROM python:3.10-slim AS builder

WORKDIR /build

COPY requirements.txt .

RUN python -m venv /opt/venv

RUN /opt/venv/bin/pip install \
    --no-cache-dir \
    -r requirements.txt


# -------------------------
# Stage 2: Runtime
# -------------------------
FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY app.py .

EXPOSE 5000

CMD ["python", "app.py"]